/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PostRequirementRouteImport } from './routes/post-requirement'
import { Route as MapRouteImport } from './routes/map'
import { Route as JoinCarpenterRouteImport } from './routes/join-carpenter'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CarpenterIdRouteImport } from './routes/carpenter.$id'
import { Route as BookServiceServiceIdRouteImport } from './routes/book-service.$serviceId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedVendorReferralsRouteImport } from './routes/_authenticated/vendor.referrals'
import { Route as AuthenticatedVendorProjectsRouteImport } from './routes/_authenticated/vendor.projects'
import { Route as AuthenticatedVendorProfileRouteImport } from './routes/_authenticated/vendor.profile'
import { Route as AuthenticatedVendorProductsRouteImport } from './routes/_authenticated/vendor.products'
import { Route as AuthenticatedVendorOrdersRouteImport } from './routes/_authenticated/vendor.orders'
import { Route as AuthenticatedVendorLeadsRouteImport } from './routes/_authenticated/vendor.leads'
import { Route as AuthenticatedVendorBookingsRouteImport } from './routes/_authenticated/vendor.bookings'
import { Route as AuthenticatedVendorBlogRouteImport } from './routes/_authenticated/vendor.blog'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin.vendors'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminReelsRouteImport } from './routes/_authenticated/admin.reels'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as CarpentersCityAreaServiceRouteImport } from './routes/carpenters.$city.$area.$service'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRequirementRoute = PostRequirementRouteImport.update({
  id: '/post-requirement',
  path: '/post-requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCarpenterRoute = JoinCarpenterRouteImport.update({
  id: '/join-carpenter',
  path: '/join-carpenter',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarpenterIdRoute = CarpenterIdRouteImport.update({
  id: '/carpenter/$id',
  path: '/carpenter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceServiceIdRoute = BookServiceServiceIdRouteImport.update({
  id: '/book-service/$serviceId',
  path: '/book-service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedVendorReferralsRoute =
  AuthenticatedVendorReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProjectsRoute =
  AuthenticatedVendorProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProfileRoute =
  AuthenticatedVendorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorProductsRoute =
  AuthenticatedVendorProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorOrdersRoute =
  AuthenticatedVendorOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorLeadsRoute =
  AuthenticatedVendorLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorBookingsRoute =
  AuthenticatedVendorBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorBlogRoute = AuthenticatedVendorBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedVendorRoute,
} as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReelsRoute = AuthenticatedAdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CarpentersCityAreaServiceRoute =
  CarpentersCityAreaServiceRouteImport.update({
    id: '/carpenters/$city/$area/$service',
    path: '/carpenters/$city/$area/$service',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-carpenter': typeof JoinCarpenterRoute
  '/map': typeof MapRoute
  '/post-requirement': typeof PostRequirementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/reels': typeof ReelsRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/shops': typeof ShopsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/book-service/$serviceId': typeof BookServiceServiceIdRoute
  '/carpenter/$id': typeof CarpenterIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/blog': typeof AuthenticatedVendorBlogRoute
  '/vendor/bookings': typeof AuthenticatedVendorBookingsRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/projects': typeof AuthenticatedVendorProjectsRoute
  '/vendor/referrals': typeof AuthenticatedVendorReferralsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
  '/carpenters/$city/$area/$service': typeof CarpentersCityAreaServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-carpenter': typeof JoinCarpenterRoute
  '/map': typeof MapRoute
  '/post-requirement': typeof PostRequirementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/reels': typeof ReelsRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/shops': typeof ShopsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book-service/$serviceId': typeof BookServiceServiceIdRoute
  '/carpenter/$id': typeof CarpenterIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/vendor/blog': typeof AuthenticatedVendorBlogRoute
  '/vendor/bookings': typeof AuthenticatedVendorBookingsRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/projects': typeof AuthenticatedVendorProjectsRoute
  '/vendor/referrals': typeof AuthenticatedVendorReferralsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/carpenters/$city/$area/$service': typeof CarpentersCityAreaServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-carpenter': typeof JoinCarpenterRoute
  '/map': typeof MapRoute
  '/post-requirement': typeof PostRequirementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/reels': typeof ReelsRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/shops': typeof ShopsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/book-service/$serviceId': typeof BookServiceServiceIdRoute
  '/carpenter/$id': typeof CarpenterIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/vendor/blog': typeof AuthenticatedVendorBlogRoute
  '/_authenticated/vendor/bookings': typeof AuthenticatedVendorBookingsRoute
  '/_authenticated/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/_authenticated/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/_authenticated/vendor/products': typeof AuthenticatedVendorProductsRoute
  '/_authenticated/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/_authenticated/vendor/projects': typeof AuthenticatedVendorProjectsRoute
  '/_authenticated/vendor/referrals': typeof AuthenticatedVendorReferralsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/carpenters/$city/$area/$service': typeof CarpentersCityAreaServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/forgot-password'
    | '/join-carpenter'
    | '/map'
    | '/post-requirement'
    | '/privacy-policy'
    | '/projects'
    | '/reels'
    | '/requirements'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/shops'
    | '/terms-of-service'
    | '/verify-email'
    | '/wishlist'
    | '/admin'
    | '/profile'
    | '/vendor'
    | '/blog/$slug'
    | '/book-service/$serviceId'
    | '/carpenter/$id'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reels'
    | '/admin/services'
    | '/admin/vendors'
    | '/vendor/blog'
    | '/vendor/bookings'
    | '/vendor/leads'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/projects'
    | '/vendor/referrals'
    | '/admin/'
    | '/vendor/'
    | '/carpenters/$city/$area/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/forgot-password'
    | '/join-carpenter'
    | '/map'
    | '/post-requirement'
    | '/privacy-policy'
    | '/projects'
    | '/reels'
    | '/requirements'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/shops'
    | '/terms-of-service'
    | '/verify-email'
    | '/wishlist'
    | '/profile'
    | '/blog/$slug'
    | '/book-service/$serviceId'
    | '/carpenter/$id'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reels'
    | '/admin/services'
    | '/admin/vendors'
    | '/vendor/blog'
    | '/vendor/bookings'
    | '/vendor/leads'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/profile'
    | '/vendor/projects'
    | '/vendor/referrals'
    | '/admin'
    | '/vendor'
    | '/carpenters/$city/$area/$service'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/forgot-password'
    | '/join-carpenter'
    | '/map'
    | '/post-requirement'
    | '/privacy-policy'
    | '/projects'
    | '/reels'
    | '/requirements'
    | '/reset-password'
    | '/services'
    | '/shop'
    | '/shops'
    | '/terms-of-service'
    | '/verify-email'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/vendor'
    | '/blog/$slug'
    | '/book-service/$serviceId'
    | '/carpenter/$id'
    | '/product/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reels'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/vendor/blog'
    | '/_authenticated/vendor/bookings'
    | '/_authenticated/vendor/leads'
    | '/_authenticated/vendor/orders'
    | '/_authenticated/vendor/products'
    | '/_authenticated/vendor/profile'
    | '/_authenticated/vendor/projects'
    | '/_authenticated/vendor/referrals'
    | '/_authenticated/admin/'
    | '/_authenticated/vendor/'
    | '/carpenters/$city/$area/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinCarpenterRoute: typeof JoinCarpenterRoute
  MapRoute: typeof MapRoute
  PostRequirementRoute: typeof PostRequirementRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  ReelsRoute: typeof ReelsRoute
  RequirementsRoute: typeof RequirementsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  ShopsRoute: typeof ShopsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WishlistRoute: typeof WishlistRoute
  BookServiceServiceIdRoute: typeof BookServiceServiceIdRoute
  CarpenterIdRoute: typeof CarpenterIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CarpentersCityAreaServiceRoute: typeof CarpentersCityAreaServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-requirement': {
      id: '/post-requirement'
      path: '/post-requirement'
      fullPath: '/post-requirement'
      preLoaderRoute: typeof PostRequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-carpenter': {
      id: '/join-carpenter'
      path: '/join-carpenter'
      fullPath: '/join-carpenter'
      preLoaderRoute: typeof JoinCarpenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carpenter/$id': {
      id: '/carpenter/$id'
      path: '/carpenter/$id'
      fullPath: '/carpenter/$id'
      preLoaderRoute: typeof CarpenterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-service/$serviceId': {
      id: '/book-service/$serviceId'
      path: '/book-service/$serviceId'
      fullPath: '/book-service/$serviceId'
      preLoaderRoute: typeof BookServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/vendor/referrals': {
      id: '/_authenticated/vendor/referrals'
      path: '/referrals'
      fullPath: '/vendor/referrals'
      preLoaderRoute: typeof AuthenticatedVendorReferralsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/projects': {
      id: '/_authenticated/vendor/projects'
      path: '/projects'
      fullPath: '/vendor/projects'
      preLoaderRoute: typeof AuthenticatedVendorProjectsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/profile': {
      id: '/_authenticated/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/products': {
      id: '/_authenticated/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof AuthenticatedVendorProductsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/orders': {
      id: '/_authenticated/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof AuthenticatedVendorOrdersRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/leads': {
      id: '/_authenticated/vendor/leads'
      path: '/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof AuthenticatedVendorLeadsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/bookings': {
      id: '/_authenticated/vendor/bookings'
      path: '/bookings'
      fullPath: '/vendor/bookings'
      preLoaderRoute: typeof AuthenticatedVendorBookingsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/blog': {
      id: '/_authenticated/vendor/blog'
      path: '/blog'
      fullPath: '/vendor/blog'
      preLoaderRoute: typeof AuthenticatedVendorBlogRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reels': {
      id: '/_authenticated/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AuthenticatedAdminReelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/carpenters/$city/$area/$service': {
      id: '/carpenters/$city/$area/$service'
      path: '/carpenters/$city/$area/$service'
      fullPath: '/carpenters/$city/$area/$service'
      preLoaderRoute: typeof CarpentersCityAreaServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReelsRoute: typeof AuthenticatedAdminReelsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReelsRoute: AuthenticatedAdminReelsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendorRouteChildren {
  AuthenticatedVendorBlogRoute: typeof AuthenticatedVendorBlogRoute
  AuthenticatedVendorBookingsRoute: typeof AuthenticatedVendorBookingsRoute
  AuthenticatedVendorLeadsRoute: typeof AuthenticatedVendorLeadsRoute
  AuthenticatedVendorOrdersRoute: typeof AuthenticatedVendorOrdersRoute
  AuthenticatedVendorProductsRoute: typeof AuthenticatedVendorProductsRoute
  AuthenticatedVendorProfileRoute: typeof AuthenticatedVendorProfileRoute
  AuthenticatedVendorProjectsRoute: typeof AuthenticatedVendorProjectsRoute
  AuthenticatedVendorReferralsRoute: typeof AuthenticatedVendorReferralsRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
}

const AuthenticatedVendorRouteChildren: AuthenticatedVendorRouteChildren = {
  AuthenticatedVendorBlogRoute: AuthenticatedVendorBlogRoute,
  AuthenticatedVendorBookingsRoute: AuthenticatedVendorBookingsRoute,
  AuthenticatedVendorLeadsRoute: AuthenticatedVendorLeadsRoute,
  AuthenticatedVendorOrdersRoute: AuthenticatedVendorOrdersRoute,
  AuthenticatedVendorProductsRoute: AuthenticatedVendorProductsRoute,
  AuthenticatedVendorProfileRoute: AuthenticatedVendorProfileRoute,
  AuthenticatedVendorProjectsRoute: AuthenticatedVendorProjectsRoute,
  AuthenticatedVendorReferralsRoute: AuthenticatedVendorReferralsRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
}

const AuthenticatedVendorRouteWithChildren =
  AuthenticatedVendorRoute._addFileChildren(AuthenticatedVendorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinCarpenterRoute: JoinCarpenterRoute,
  MapRoute: MapRoute,
  PostRequirementRoute: PostRequirementRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  ReelsRoute: ReelsRoute,
  RequirementsRoute: RequirementsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  ShopsRoute: ShopsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WishlistRoute: WishlistRoute,
  BookServiceServiceIdRoute: BookServiceServiceIdRoute,
  CarpenterIdRoute: CarpenterIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  CarpentersCityAreaServiceRoute: CarpentersCityAreaServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
